const INVITATION_HEX_LENGTH = 20;

/**
 * Firestore document ids must be collision-resistant across browsers and POS terminals.
 * UUIDs are generated by the platform CSPRNG and remain compatible with the existing
 * alpha-numeric/dash security-rule constraint.
 */
export function createDocumentId(prefix: string): string {
  return `${prefix}-${crypto.randomUUID()}`;
}
/**
 * Invitation codes are typed by people but also act as bearer credentials. Twenty random
 * hexadecimal characters provide 80 bits of entropy, unlike the old five-digit code which
 * could be exhaustively queried.
 */
export function createInvitationCode(): string {
  const randomHex = crypto.randomUUID().replaceAll('-', '').slice(0, INVITATION_HEX_LENGTH).toUpperCase();
  return `INV-${randomHex}`;
}

